name: Build & Deploy React to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # biar bisa manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Build & Push Docker Image
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/event-apps:latest

      # 2. Deploy ke VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            # Login ke Docker Hub
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # Pull image terbaru
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/event-apps:latest

            # Stop & hapus container lama (jika ada)
            sudo docker stop event-apps || true
            sudo docker rm event-apps || true

            

            # Jalankan container baru
            sudo docker run -d \
              --name event-apps \
              -p 3000:3000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/event-apps:latest

            sudo docker network connect npm-networks event-apps|| true

            # Logout (opsional)
            sudo docker logout